### ISSUE TITLE
Story counts in the editor are off

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#100]
>Kosovo (Telugu Contributor) — Yesterday at 11:46 AM
just a question - what do the numbers next to the courses mean?
![image](https://user-images.githubusercontent.com/4418961/171042155-4adfff71-0c08-4b44-84cd-4f64ed2caaf6.png)

>randrian 🇩🇪🇪🇸🇫🇷🇺🇸 — Today at 11:47 AM
The numbers are supposed to show the number of stories. But somehow this got messed up. I have to look into that again.

**Comment by rgerum** [comment]
Fixed (540a24684b547a4a22fe00b31cca9f164a4d3eef)
