### ISSUE TITLE
Clicking the "RESET" link after creating an account results in a missing reset button

### ISSUE THREAD

**Issue by PineappleSnackz** [rgerum/unofficial-duolingo-stories#107]
Attempting to go to the reset password form right after signing up causes the reset button to not show up.
![msedge_jw5BKPP4j8](https://user-images.githubusercontent.com/47675689/171457962-3f3f3f51-a9bf-4a16-877f-29802e9a6d97.png)

**Comment by onfranciis** [comment]
I would love to analyse this, @rgerum  how do I get access to full content, should I create an account?

**Comment by rgerum** [comment]
If you don't yet have an account on the www.duostories.org website you should make one and I can give you access to the editor. For this part you do not need the access to the editor though. Or which other content to you mean? Direct access to the mysql database should not be necessary to work with the front end.

If you need to create test accounts to investigate how things show up directly after signing up, please prefix your account names with test_ to indicate that these accounts an be removed at some point later on.

**Comment by onfranciis** [comment]
> If you don't yet have an account on the [www.duostories.org](http://www.duostories.org) website you should make one and I can give you access to the editor. For this part you do not need the access to the editor though. Or which other content to you mean? Direct access to the mysql database should not be necessary to work with the front end.
> 
> If you need to create test accounts to investigate how things show up directly after signing up, please prefix your account names with test_ to indicate that these accounts an be removed at some point later on.

I'll do the later right now
