### ISSUE TITLE
Clear Form On Registration

### ISSUE THREAD

**Issue by onfranciis** [rgerum/unofficial-duolingo-stories#115]
While creating an account, after the user has inputed the details, the form should be cleared

I want to resolve it.

**Comment by rgerum** [comment]
Yes, makes sense.

**Comment by rgerum** [comment]
@onfranciis do you still want to work on this? It has been open for quite some time.

**Comment by onfranciis** [comment]
Yes I do, please bear with me

**Comment by onfranciis** [comment]
@rgerum While I was on this, I discovered you made a custom hook to accept inputs. Any reason behind this?
Because using a usestate would have been better.

**Comment by rgerum** [comment]
well the useState does need a wrapper for the setstate function to be used directly as the state change function of the <input> field. with my custom hook I provide this wrapper around the setstate function useState provides.
