### ISSUE TITLE
Multiple translations for words

### ISSUE THREAD

**Issue by IFrzzl** [rgerum/unofficial-duolingo-stories#127]
Would it be possible to add multiple translations for a word or phrase in the editor?
For example, Duolingo does it as shown in the image.

![839319E8-E42F-40A7-AA3B-0F92460A67BF](https://user-images.githubusercontent.com/83833754/179402553-b97e9254-0f89-43cd-bef9-af6d4cea3d88.jpeg)

**Comment by rgerum** [comment]
As duolingo does not have his for stories and it is a lot of effort to implement this with a very minimal benefit, I have no current plans to implement this.
