### ISSUE TITLE
Alphabetize story languages on homepage

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#128]
Right now the story languages aren't in any discernible order. It'd be easier to find the language you're looking for if they were alphabetized.

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/4418961/179445633-85f8f751-998e-46ef-bcae-2fb02dd0db3f.png">

**Comment by ptoro** [comment]
Ah, so that's the order.

> Maybe it would be good to print the number of sets/stories below the language name.

Definitely helpful. Though I think alphabetical is easier to find than by number of sets. If you show number of sets per language and list the languages in alphabetical order, you get both the benefits.

**Comment by rgerum** [comment]
Well when someone comes to the website and clicks on one of the courses it would be good that the visitor sees a course with a lot of stories. If we hide the relevant courses somewhere down in the alphabet it might seem that the website does not have much material. But well maybe if we show the number of sets or stories people see how much material there is directly from the main page.

**Comment by ptoro** [comment]
My product philosophy is almost always to support the most common use case first. I don't have a view at the analytics to be able to determine what the primary use case is here, but my intuition leads me to think the primary use case is users come for stories in the language they want to learn. Alphabetized stories best fit that use case by allowing users to quickly find their language.

For example, I don't think users coming to learn Arabic much care how many Greek stories there are. But, if you want to show the wealth of available material, I can think of a few ways to do that without hampering the primary use case. One idea: you could add a sentence with a total story count to the frontpage like:

>159 stories in 34 languages and counting!

(right between the current first [A community project...] and second lines [If you want to contribute...] seems like a good fit content-wise) and have that automatically increase as new stories are published.

Regardless of the order, though, I think showing the number of available stories is a great idea.
