### ISSUE TITLE
Fonts for sitelen pona (tok)

### ISSUE THREAD

**Issue by JohnathanHarvey** [rgerum/unofficial-duolingo-stories#130]
We would like to be able to use sitelen pona within duostories. The preferred implementation of this would be a separate course, like Simplified and Traditional Chinese. Despite toki pona having an ISO code, we don't yet have sitelen pona in unicode, so for now, it is a font.

I will also look into making a PR adding this, but I'm not a PHP dev so it will probably need heavy review.

[Docs for the font](https://docs.google.com/document/d/1d8kUIAVlB-JNgK3LWr_zVCuUOZTh2hF7CfC6xQgxsBs/edit)
[Github](https://github.com/janSame/linja-pona)
[Example 1](https://wyub.github.io/tokipona/linjasike), [Example 2](https://linjasuwi.ap5.dev/)

edit: My discord name is jan Paje if you want to contact me

**Comment by rgerum** [comment]
I guess the most problematic thing here is that it is not intrinsically clear which texts are in the target language (where the desired font should be applied) and which texts are in the base language (with the default font). Especially for the questions they can be in the target or the base language.

**Comment by rgerum** [comment]
I now implemented an option to have different fonts for the base language and the learning language. So if you still want, we can now open a course for Toki Pona with sitelen pona.
