### ISSUE TITLE
The editor mobile login page should be formatted for mobile like the homepage mobile login page

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#132]
The editor mobile login page (editor.duostories.org) is currently formatted for desktop and as such requires zooming in to be at the right size: 
![Screenshot_20220810-222839.png](https://user-images.githubusercontent.com/4418961/184055079-2e7b87d4-4fa5-43b6-b4bd-d663ba9fe66a.png)

It should match the homepage's mobile login page (duostories.org/login):
![Screenshot_20220810-215505.png](https://user-images.githubusercontent.com/4418961/184054962-0851cbdc-63e4-486b-a2cd-6da913de85fb.png)

**Comment by rgerum** [comment]
Yes we can do that. But unfortunately the rest of the editor is not formatted for mobile anyway. And it would require a lot more effort to redesign the editor to completely work for mobile.

**Comment by ptoro** [comment]
Now that @PaoloDiBello has added pull requests to start making the editor more mobile-friendly (https://github.com/rgerum/unofficial-duolingo-stories/pull/135, https://github.com/rgerum/unofficial-duolingo-stories/pull/133), I figured it'd be beneficial to start making improvements from the beginning of the mobile experience.

**Comment by rgerum** [comment]
the editor now uses the same login page as the main app.
