### ISSUE TITLE
Story languages are not in alphabetical order on homepage

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#136]
To make it easier to find stories by language, the languages should be in alphabetical order on the homepage. E.g. in the image below the order should be French Speakers, Italian Speakers, Portuguese Speakers.

Right now the story languages aren't in any discernible order. This isn't a big deal right now with only 7 languages other than English, but will become more important as we add more learning-from languages.

![image](https://user-images.githubusercontent.com/4418961/184576832-61053d37-6925-472e-9ba7-a3451b42c3bb.png)

**Comment by rgerum** [comment]
I changed it to alphabetical. But I kept nevertheless English as the first one because its the probably most relevant for the average user.
