### ISSUE TITLE
Login fails with complicated password (long or special characters)

### ISSUE THREAD

**Issue by oliverklee** [rgerum/unofficial-duolingo-stories#147]
## Summary

I cannot log in with a new user, even after changing the password.

## Steps to reproduce
1. go to https://www.duostories.org/
2. click on the green "log in" button
3. click on the "sign up" link
4. enter a user name, email and password
5. click on "sign up"
6. navigate to the login form
7. enter the user name and password from above
8. see the error message "Wrong username or password. Try again."
9. click on "reset"
10. enter the user name
11. click on the "reset" button
12. click on the link in the email
13. enter a new password
14. use the submit button
15. try to login with the new password and the existing user name

## Expected results
I'm able to log in with my credentials, and I'm also able to log in with the changed password.

## Actual results
Both times, I get the "Wrong username or password. Try again." error rmesage, and am not logged in.

## Additional information
My username is "oliverklee", I used my @hey.com email address (oliver.klee@), and first used a LastPass-generated 16-letter password like "V2z3^o*yFDRE1^ar" and then used something simpler like "as741kq!j2345" for the passoword reset.

This is on Firefox 104.0.1 on Kubuntu Linux.

**Comment by PaoloDiBello** [comment]
Hi @oliverklee, 
Can you give more details on how the requests responds whenever you try to log in or errors showed in the console?
Have you tried changing the password to something simpler or trying to log in from another OS?

Thanks.

**Comment by oliverklee** [comment]
After I have entered my current credentials at https://www.duostories.org/login and clicked the login button, the HTTP POST request to https://www.duostories.org/stories/backend/user/user.php?action=login results in a 403 forbidden response.

I've noticed that the request headers contain a cookie with a username (which contains my email address, not my user name) and my password, which seems odd to me.

**Comment by oliverklee** [comment]
After I have deleted the cookie, the login still does not work.

There are no error messages on the console when the login fails.

**Comment by oliverklee** [comment]
Ah, this is very strange: Changing my password to something simple (8 letters only, only numbers and lowercase letters) and deleting the cookie did the trick. This smells like either an encoding problem when transmitting the password or when doing the DB query, or unhashed passwords.

**Comment by steventhorne** [comment]
I also cannot login even after resetting my password to something simple like 'hello'. I get a 200 response back from `https://www.duostories.org/stories/backend/user/user.php?action=login`, but the body of the response has the following message:

```
Notice: Undefined variable: db in /var/www/virtual/carex/html/stories/backend/user/user.php on line 101

Warning: mysqli_escape_string() expects parameter 1 to be mysqli, null given in /var/www/virtual/carex/html/stories/backend/user/user.php on line 101

Notice: Undefined variable: db in /var/www/virtual/carex/html/stories/backend/user/user.php on line 102

Warning: mysqli_query() expects parameter 1 to be mysqli, null given in /var/www/virtual/carex/html/stories/backend/user/user.php on line 102

Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, null given in /var/www/virtual/carex/html/stories/backend/user/user.php on line 102

Notice: Trying to access array offset on value of type null in /var/www/virtual/carex/html/stories/backend/user/user.php on line 103

Notice: Undefined variable: db in /var/www/virtual/carex/html/stories/backend/user/user.php on line 101

Warning: mysqli_escape_string() expects parameter 1 to be mysqli, null given in /var/www/virtual/carex/html/stories/backend/user/user.php on line 101

Notice: Undefined variable: db in /var/www/virtual/carex/html/stories/backend/user/user.php on line 102

Warning: mysqli_query() expects parameter 1 to be mysqli, null given in /var/www/virtual/carex/html/stories/backend/user/user.php on line 102

Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, null given in /var/www/virtual/carex/html/stories/backend/user/user.php on line 102

Notice: Trying to access array offset on value of type null in /var/www/virtual/carex/html/stories/backend/user/user.php on line 103
check1
yes
Array ( [user] => Array ( [id] => 4427 [username] => **REDACTED** [password] => **REDACTED** [email] => **REDACTED** [regdate] => 2022-09-11 23:31:46 [role] => 0 [admin] => 0 [activated] => 1 [activation_link] => **REDACTED** ) ) 
```

**Comment by oliverklee** [comment]
An update from my side: I can now consistently and successfully log in using my simpler password as long as I am not using the "keep me logged in" checkbox.

**Comment by oliverklee** [comment]
Update: The login works on Safari on my iOS and iPadOS devices, but not on Firefox on Linux.

**Comment by rgerum** [comment]
I fixed how cookies are stored to encode special characters. (9f9378bbbd6be292f28df92a6911cf4035c1c214)
I hope the login works now.

**Comment by oliverklee** [comment]
Thanks, now I can log in even with a reasonably complicated password on Firefox/Linux with and without the "remember me" option.

Safari on iPadOS works, too.

Thanks for fixing this! :heart:
