### ISSUE TITLE
Debug message on the browser console when playing a story

### ISSUE THREAD

**Issue by oliverklee** [rgerum/unofficial-duolingo-stories#149]
I'd expected debug output on the console only to be displayed if a debug switch is set. I don't expect it to be displayed by default.

## Steps to reproduce
1. open the browser console
2. go to https://www.duostories.org/
3. click on "Dutch"
4. click on the first story "Good morning"

## Expected results
no debug output on the console

## Actual results
lots of debug output on the console (see screenshot)
![grafik](https://user-images.githubusercontent.com/765746/188310664-91b548f8-6857-4666-a6b4-d21170399080.png)

## Additional information
This is with Firefox on Linux.

**Comment by PaoloDiBello** [comment]
There is a console log in question-match.js in the function QuestionMatch

`console.log(orderA, orderB, order);`
