### ISSUE TITLE
Stories with audio are not loading on iOS Safari

### ISSUE THREAD

**Issue by exil** [rgerum/unofficial-duolingo-stories#151]
iOS version: 15.6.1
Phone: iPhone 13 Pro

Ever since I believe bc22f29d8f421c5a7983faef782fbe736b78d4c2, clicking on an individual story with audio, such as one in Greek, on iOS Safari shows the loading graphic indefinitely. (Note that there also seems to be an unrelated bug where stories without audio URLs such as Arabic are not loading regardless of browser.) 

It seems to be due to the `canplaythrough` event not firing. (See [StackOverflow](https://stackoverflow.com/questions/49792768/js-html5-audio-why-is-canplaythrough-not-fired-on-ios-safari))

I have a proposed change on my forked repo (5d3469fce5ba00ee8f2f9bd728160f9d07dbc9d2). If this issue is approved and this solution is OK, I can open a pull request.

**Comment by rgerum** [comment]
oh simply a.load() fixes the issue? seems to be a simple change. I don't know if it then creates other issues though, e.g. loading the audio twice

**Comment by exil** [comment]
> oh simply a.load() fixes the issue? seems to be a simple change. I don't know if it then creates other issues though, e.g. loading the audio twice
> 
> 

Yeah, it at least fixes the issue for iOS. I actually was also wondering if it would load the audio twice. I can look into that a bit more.

**Comment by rgerum** [comment]
But it still might be a good hot fix. I really should get a test environment with safari :-/
