### ISSUE TITLE
Certain stories do not load

### ISSUE THREAD

**Issue by exil** [rgerum/unofficial-duolingo-stories#152]
Browser: Chrome 105.0.5195.102 (also tested on Firefox 104.0.2)
OS: macOS 12.5.1

Certain stories do not load, such as this one here: https://www.duostories.org/story/1893
Other stories load fine, such as https://www.duostories.org/story/989

The console shows
```
GET https://carex.uber.space/stories/undefined 404
```

It may be because the `get_story_json.php` call is missing audio URLs.

**Comment by rgerum** [comment]
This story works now with my fix for stories without audio.
