### ISSUE TITLE
Continue keyboard shortcut in stories should consistently continue

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#157]
Inspired by kindlyinsertyourusernamehere's comment on Discord

Right now `[Enter]` works to continue to the next line of the story only sometimes. Pressing `[Enter]` should continue the story anytime the Continue button is present. Right now it doesn't work at the beginning of the story:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/4418961/193677981-5aac3a17-8ff8-4746-9417-fddcd94ab512.png">

It also doesn't work after selecting an option in an exercise:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/4418961/193678092-18ed8c75-a5c4-4ade-b9c5-d8a915a37693.png">

**Comment by rgerum** [comment]
No yet on the production server, but you can test on the test server: https://test.duostories.org

**Comment by ptoro** [comment]
Just tested on the test server. Everything works except for the last button after you finish the story (the Finish button).
