### ISSUE TITLE
Save button confirmation

### ISSUE THREAD

**Issue by simonbromberg** [rgerum/unofficial-duolingo-stories#169]
Would be nice if tapping "Save" on the editor showed a confirmation of some kind

**Comment by rgerum** [comment]
I added a * symbol to the save button when the story has unsaved changes. I hope this addresses the issue sufficiently. I thought a popup dialog would be to intrusive if people save their work regularly. You get a pop up dialog if things go wrong for some reason tough.

**Comment by simondelphia** [comment]
Yea a pop up would probably be annoying. I think the asterisk is a good idea without making it too complicated.

**Comment by simonbromberg** [comment]
that sounds good to me
