### ISSUE TITLE
Allow text to be selected

### ISSUE THREAD

**Issue by krisl** [rgerum/unofficial-duolingo-stories#174]
for those that might have a translator extension installed in their browser

**Comment by rgerum** [comment]
Do you think the hints are not sufficient for the stories? I tried to mimic the behaviour of the original Duolingo stories they also don't have the ability to select text. But I think it also should not be too much of an issue to implement. I am just wondering if there might be some reasons why Duolingo implemented it this way. So there might be some issues associated with select-able text.

**Comment by krisl** [comment]
I think mostly for the latin script ones perhaps they are sufficient, cyrillic, or other phonetic.
But with Chinese characters I know I at least personally use a translator a lot to lookup single characters, words.

In Duolingo I can highlight the text.
<img width="642" alt="image" src="https://user-images.githubusercontent.com/782873/201991062-6e5042ab-b0cf-4e17-ab11-b474519aefe0.png">

eg, here I have just double clicked the line to highlight, and my translator extension pops up

Yeah, sometimes there are some small conflicts with highlighting text.  Eg it highlights some hidden text that may include a translation so you can get some mixed languages coming through.

**Comment by krisl** [comment]
Further to this, sometimes, duolingo for example but also other language learning sites, give a very "culturally equivalent" translation, and sometimes you want a hyper-literal translation.  So these kinds of plugins are handy and I find myself translating one word, then two words, then two other words in a sentence for example, trying to understand the structure.

**Comment by rgerum** [comment]
ok yes makes sense. I will have a look to implement text selection should be only a css change.
