### ISSUE TITLE
Save Dark Mode Settings to Local Storate

### ISSUE THREAD

**Issue by CoryDerGrosse** [rgerum/unofficial-duolingo-stories#182]
When the user changes the dark mode setting, save this choice to the browser's local storage.  This will prevent the dark mode choice from being reset upon refreshing or leaving and revisiting the page.

**Comment by CoryDerGrosse** [comment]
P.S.  I am interested in working on this issue myself, but am unable to assign it to myself per the "How to Contribute" section.

**Comment by rgerum** [comment]
Sounds like a good idea. Please go ahead, I assigned you to the issue.
