### ISSUE TITLE
profile drop down menu can get out of screen

### ISSUE THREAD

**Issue by rgerum** [rgerum/unofficial-duolingo-stories#198]

**Comment by CoryButler** [comment]
Hey, I was hoping to make a suggestion on a minor UI upgrade to the <nav> at the top of the page.  Then I saw this open issue.  Do you mind if I take a crack at this and add a couple other CSS changes to the dropdown menus at the same time?
![image](https://user-images.githubusercontent.com/24963579/234365634-e39cee7e-a82b-4bd3-8fba-d24d2f107819.png)
![image](https://user-images.githubusercontent.com/24963579/234365719-8b83cb9e-a775-434a-b280-8c0ef98ddbec.png)

**Comment by rgerum** [comment]
yes you can have a go. I assigned you. Be sure to edit the version in the next folder as this is the version of the code that is currently used, I will remove the other code soon.

**Comment by CoryDerGrosse** [comment]
Hey, I was hoping to make a suggestion on a minor UI upgrade to the
at the top of the page. Then I saw this open issue. Do you mind if I take a crack at this and add a couple other CSS changes to the dropdown menus at the same time?
![image](https://user-images.githubusercontent.com/120683089/234581673-149662b3-8108-47cf-a510-c572a552d75c.png)
![image](https://user-images.githubusercontent.com/120683089/234581686-33e9229e-e0ab-48de-9248-bfbe358b48b4.png)

**Comment by rgerum** [comment]
Be sure to test it in different browsers. For example for me in Firefox it already looks like your example on the right. For me the only problem is on very small screens that the drop-down menu exeeds the screen a bit.

**Comment by meddhiaka** [comment]
Hey @rgerum,

I'm interested in working on this pull request.

Thanks!

**Comment by rgerum** [comment]
fixed now (075521074acdddee4cb820080f90dc862b619918)
