### ISSUE TITLE
No sound on Mobile

### ISSUE THREAD

**Issue by Sermim** [rgerum/unofficial-duolingo-stories#199]
I have tried turning off and on my phone but there’s no sound for the dutch stories… anyone else noticed the same issue? The achievements sounds is working fine but not the character voices

**Comment by rgerum** [comment]
for me it works. Maybe its a specific Dutch story?

**Comment by Sermim** [comment]
On the computer it works. I tested on 2 different IOS mobiles and it doesn’t work. Maybe only works on Android?

**Comment by Sermim** [comment]
> for me it works. Maybe its a specific Dutch story?

There isn’t sound for any of the stories

**Comment by rgerum** [comment]
Oh you are right, I had a friend try it on their iPhone and it did not work.

**Comment by ofou** [comment]
same here, not working audio on ios

**Comment by rgerum** [comment]
I made some progress on this bug. It seems that there is a problem with the data types of the audio files. Some audio files are actually .wav files and not .mp3 files. Some browsers do not seem to mind but others have a problem with me trying to sell ".wav" files as ".mp3". I hope that converting them will solve the issue.

**Comment by rgerum** [comment]
The issue should be solved now. All audio files are now .mp3 files and new files that are created will be directly .mp3 files.

**Comment by Sermim** [comment]
Thank you very much, it's working now :))))
