### ISSUE TITLE
Ich möchte dazu beitragen, mehr Stories in den Italienischkurse auf Englisch zu hinzufügen

### ISSUE THREAD

**Issue by PaoloDiBello** [rgerum/unofficial-duolingo-stories#20]
I want to contribute to add new italian stories for english speakers

**Comment by PaoloDiBello** [comment]
This shouldn't be really considered to an issue, I will close it as soon as I get a response from you.

- [ ] Activate my account: PaoloDiBello

**Comment by rgerum** [comment]
I did send you an invitation email.
