### ISSUE TITLE
Database of Doulingo stories

### ISSUE THREAD

**Issue by thetessen** [rgerum/unofficial-duolingo-stories#22]
Your application is great. I also want to make a similar website of yours to practice but have data problem. Can I contact you to talk about the database problem? Thanks !

**Comment by rgerum** [comment]
Yes, I can try to help you with your database. What is the problem you are fighting with?

**Comment by thetessen** [comment]
Tôi đã làm xong UI cho ứng dụng. Nhưng tôi không có đầy đủ dữ liệu. Bạn có thể chia sẽ database của bạn với tôi được không hoặc tôi có thể mua nó.

**Comment by thetessen** [comment]
I have finished the UI for the application. But I don't have enough data. Can you share your database with me or I can buy it.

**Comment by rgerum** [comment]
Well, I don't know what kind of data you are talking about. I have a database with translations of the duolingo stories. But this is not what you need. You need the duolingo training sentences, if I understood your project correctly.

**Comment by thetessen** [comment]
So what is the database you use for doulingo stories? Or do you get data through Doulingo's API?

**Comment by rgerum** [comment]
Ah you mean the data of the stories that we translate. Yes, I got them through the Duolingo API. I wrote a script that downloads the data from every story. I think it might be a bit more difficult to download the lessons data. But I haven't looked onto that yet. Also you need to get permission from Duolingo if you want to use their content on your site. They have the copyright of their own stuff. But I guess your project is more about adding new courses? Or what is the idea behind your project?

**Comment by kommaqueen** [comment]
Given that the Duolingo Stories from the original languages are no longer available like they were before (instead hidden/nested within lessons), I think it would be great to add those to the database :D
