### ISSUE TITLE
Visibility Issue with GitHub and Discord SVG Icons in Light Mode

### ISSUE THREAD

**Issue by PaoloDiBello** [rgerum/unofficial-duolingo-stories#244]
## Steps to Reproduce:

1. Login to the application.
2. Ensure that light mode is enabled.
3. Navigate to the user profile.
4. Scroll down to the linked accounts section.

## Expected Behavior:
The GitHub and Discord SVG icons should be visible and distinguishable in light mode.

## Actual Behavior:
The icons are currently displayed in white, making them difficult to see against the light background in light mode.

## Additional Information:

This issue is observed in light mode.
The problem is specifically with the color of GitHub and Discord SVG icons.
Other icons are displaying correctly.

## Screenshot:
![image](https://github.com/rgerum/unofficial-duolingo-stories/assets/36816681/ed35fa08-f9ce-4b80-9a0c-0c7108e24522)

## Suggestions:
Since the image tag was used, you could use this CSS snippet when light-mode is enabled.

```css
  filter: invert(1);
```

**Comment by PaoloDiBello** [comment]
Since the image is shown dinamically using ```src={`https://authjs.dev/img/providers/${d}.svg/`}``` in `src/app/(stories)/(main)/profile/button.jsx` it might be more challenging and might add the style if a condition is met.

**Comment by rgerum** [comment]
I guess we would need to use custom icons. Maybe like the instagram/twitter/... icons with a css color that it changed with the color scheme.

**Comment by PaoloDiBello** [comment]
@rgerum Yeah, that could work too. It is generally safer to have your own hosted images/svgs.

**Comment by PaoloDiBello** [comment]
@rgerum it's still the same for me

**Comment by rgerum** [comment]
Did you try the beta page? https://beta.duostories.org/auth/signin?callbackUrl=https%3A%2F%2Fbeta.duostories.org%2F
![image](https://github.com/rgerum/unofficial-duolingo-stories/assets/14153051/ea496c6f-ef50-4e58-aa33-3a3576d2ab3a)

**Comment by PaoloDiBello** [comment]
@rgerum The problem is in the profile page

**Comment by rgerum** [comment]
Ah ok. I saw the problem on the login page. The problem was in two places. Sorry my fault, I should have read your post more carefully.

**Comment by rgerum** [comment]
![image](https://github.com/rgerum/unofficial-duolingo-stories/assets/14153051/9928173e-6e38-4087-80ac-755f21c8c887)

**Comment by rgerum** [comment]
Now I also added the icons to the profile page. (https://beta.duostories.org/profile) Thanks for checking if it was actually fixed.
