### ISSUE TITLE
The title should use the Feather font

### ISSUE THREAD

**Issue by PaoloDiBello** [rgerum/unofficial-duolingo-stories#249]
https://d35aaqx5ub95lt.cloudfront.net/vendor/68d22534874c554b0c9ebabea379fc60.woff2

Or https://colab.research.google.com/drive/1re3AU_kHTmyWmB9vEcfBXmLFGJXftdcJ

**Comment by rgerum** [comment]
I am not sure what the feather font is and why it should be used here. Which part to you refer to with "title"? The "Unofficial Duolingo Stories" on the main page or the titles of the stories.
I also cannot open the woff2 file without installing extra software. I would appreciate more information for this issue.

**Comment by PaoloDiBello** [comment]
@rgerum I mean the Duostories title

**Comment by rgerum** [comment]
ah you mean the logo-like title in the upper left corner.
Ah and the feather font is from Duolingo. But I guess I have to check what the license of this font is. As for the website I also don't use the font that Duolingo is using as it is licensed and Duolingo recommends to use Nunito instead.

**Comment by PaoloDiBello** [comment]
@rgerum Maybe we can make it an image rather than import the actual font?

**Comment by rgerum** [comment]
well as Duolingo created the font they have the right to control who and how people use it. And the did not release it in public domain. But I think that we have the license to use some duolingo material, we might also be able to get away with using this font. Although that would be pushing our boundaries I would say.

**Comment by PaoloDiBello** [comment]
Ok, I will close the issue then. This sounds like a license problem.
