### ISSUE TITLE
Audio on some stories do not play

### ISSUE THREAD

**Issue by StephanielearnsTurkish** [rgerum/unofficial-duolingo-stories#253]
I am going through the Turkish stories and some stories' audios are not playing. I noticed this yesterday and the issue continues today. 

No audio for: 
https://duostories.org/story/2072
https://duostories.org/story/2076
https://duostories.org/story/2089
https://duostories.org/story/2091

I did not go through the rest.

I have completed story 2072 before, with audio, so it is a new issue. I tried on a second device (phone) and I have the same issue. Thanks!

**Comment by PPP315** [comment]
Swedish and Norwegian Nynorsk don't either

**Comment by rgerum** [comment]
Thanks for reporting, there was an issue with coping the sound files to the new server that we currently use since a couple of days. It should be fixed now, I copied the missing files. I hope there should be none missing, if not, please report again.

**Comment by eliotmorrison** [comment]
I still see a few missing on simplified chinese
