### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by jhw** [rgerum/unofficial-duolingo-stories#33]
Just wondering if you might produce a roadmap for this project. I can see is being worked on recently, but before that not for a few months. Am guessing you are busy with other stuff. But I notice lots of people on the Duolingo forum really like it, so congrats. Do you want or need developers to help keep this project fresh ? Rgds

**Comment by rgerum** [comment]
Hi, yes I am currently working hard to make a complete revamp of the story editor. I have some quite far so far and I hope to be able to invite editors back soon. And yes probably also more developers would be good.

**Comment by jhw** [comment]
How many active users does the project have ? Do u keep stats ?

**Comment by rgerum** [comment]
I keep stats of completed stories. There are about 2500 stories done per month by an estimated number of 500 users but only 15% are resisted users (for which I have a unique identifier, the other number is extrapolated assuming the unregistered users do about the same amount of stories per user).
So the project is still actively used.

**Comment by rgerum** [comment]
@jhw I think I can close the issue here now. The project has been rebooted and we are discussing on discord (you can find the link at www.duostories.org). If you want to contribute you can either report issues or assign issues to yourself and create a pull request.
