### ISSUE TITLE
Bug: after clicking a few courses in the editor, stories show from the wrong course

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#55]
Steps to reproduce:

1. Go to the editor
2. Select a few courses
3. After clicking a few courses (~5 or so), the stories from a different course show up on the right side. See image.

Workaround: refresh the page.

<img width="1247" alt="Screen Shot 2022-04-28 at 10 44 53 PM" src="https://user-images.githubusercontent.com/4418961/165879680-64875c82-ea69-42a3-a16a-c66f8e465740.png">

**Comment by rgerum** [comment]
I removed a redundant state update that might have messed up these clicks. It seems to be fixed now, maybe you could try to confirm this to close the issue.

**Comment by ptoro** [comment]
Fixed for me! And it's faster now as well.
