### ISSUE TITLE
Bug: scrolling in the editor takes a few tries

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#56]
Steps to reproduce: 

1. Open the story editor.
2. Scroll to the bottom of the page.

Bug: the bottom of the page doesn't show.

Reproducibility: 100%

Workaround: scroll a few more times to get to the bottom

https://user-images.githubusercontent.com/4418961/165880358-0d831aeb-c965-42db-b508-6355319d17fa.mov

**Comment by rgerum** [comment]
Hmm strange behaviour. It seems that the linked scrolling is messed up. Unfortunately I cannot reproduce it. I tried with Firefox and Brave and it seems to work in both browers in your Albanian story. Maybe you can keep an eye on this issue and see if this occurs all the time or just with a certain browser.

**Comment by ptoro** [comment]
Interesting. I don't see it at all in Firefox. I only see it in Chrome. I know Brave is Chromium based but is there any way you can test in Chrome?

**Comment by rgerum** [comment]
Hmm very strange I only have the Chromium Browser here on my Linux machine, which also seems to not have the problem. I would not have thought that Chrome makes such a big difference to other Chromium Engine based browsers. Might need to see if I can install Chrome.

In case you want to have a look at the code, it is here on line 422:
https://github.com/rgerum/unofficial-duolingo-stories/blob/ab60fb44430611312e5ed6398273430552cdde24/editor-app/src/index.js#L422

I guess there is some issue with the two parts of the editor having scroll events that can trigger each other if this case it not properly caught. Which it should be but maybe Chrome uses floating point positions for scrolling and the other browsers use integer based scroll positions, but that would be just a random guess.

**Comment by ptoro** [comment]
> kam — Today at 7:29 AM
I experience issues with auto scroll in the editor

+1 from a user in the Discord server
