### ISSUE TITLE
Enhancement: Support <Enter> to login

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#58]
This is probably very low priority but also a quick one.

A common flow for signing into a website is:
1. Type username
2. Hit <Tab> to move to the password field
3. Type password
4. Hit <Enter> to log in

When I hit Enter in the password field on duostories.org, nothing happens. I have to click Log In.

Again, not a big deal. But most sites support this.

**Comment by rgerum** [comment]
Hmm that sounds like a thing that might be possible to do as a pull request if you are interested to have a look:
This is the component you would need to have a look at:
https://github.com/rgerum/unofficial-duolingo-stories/blob/master/editor-app/src/login.jsx
If you don't want to have a look I can also address the issue myself.

**Comment by onfranciis** [comment]
I'm interested, where do I start?

**Comment by rgerum** [comment]
Do you have worked with github before? You can create a fork of the repository, make a local clone and edit the file I indicated. Then you can test it by running "npm run start" in the editor-app folder. You can then commit and push your changes and create a pull request. If I approve your changes, I will merge the pull request.

**Comment by ronran1** [comment]
If @onfranciis isn't working on this, I'd love to work on it.

**Comment by onfranciis** [comment]
> Do you have worked with github before? You can create a fork of the repository, make a local clone and edit the file I indicated. Then you can test it by running "npm run start" in the editor-app folder. You can then commit and push your changes and create a pull request. If I approve your changes, I will merge the pull request.

Ok, I'll begin

**Comment by rgerum** [comment]
fixed by @onfranciis fbb57386eb523cc3ea1803f9a631e5ac0be569fd

**Comment by ptoro** [comment]
@rgerum after reading your comment on @onfranciis' commit, I realized there was a problem with my issue description.

Apparently Github markdown doesn't show angle brackets (`<`) or their content. This was the original comment before it was submitted:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/4418961/166175438-6c7c649c-69b3-45a3-8973-6e861d4cbfb4.png">
Note the `<Tab>` and `<Enter>` that are missing in the comment above.

My fault. I should have previewed the comment before posting.

Also, @onfranciis, I noticed that the functionality in this issue isn't currently working in Chrome or Firefox.

**Comment by rgerum** [comment]
Ah ok, well the flow:
enter username, press TAB, enter password, press TAB (to focus the button), press ENTER (to submit it) already worked. So you only wanted to get rid of the second press TAB step.

@onfranciis sorry that I did not accept your first version of the pull request. You apparently understood the task better than I did :-D

**Comment by ptoro** [comment]
Reopen this issue?

Also, it looks like @onfranciis' Enter functionality that he did committed (Enter to move to the next input) isn't working, at least for me in Chrome and Firefox.

**Comment by onfranciis** [comment]
> Reopen this issue?
> 
> Also, it looks like @onfranciis' Enter functionality that he did committed (Enter to move to the next input) isn't working, at least for me in Chrome and Firefox.

Try clearing your cookies
It worked on my machine (Firefox)

**Comment by onfranciis** [comment]
> Ah ok, well the flow: enter username, press TAB, enter password, press TAB (to focus the button), press ENTER (to submit it) already worked. So you only wanted to get rid of the second press TAB step.
> 
> @onfranciis sorry that I did not accept your first version of the pull request. You apparently understood the task better than I did :-D

It's Ok, I"ll work on it
Do you mind reopening the issue?

**Comment by onfranciis** [comment]
> Ah ok, well the flow: enter username, press TAB, enter password, press TAB (to focus the button), press ENTER (to submit it) already worked. So you only wanted to get rid of the second press TAB step.
> 
> @onfranciis sorry that I did not accept your first version of the pull request. You apparently understood the task better than I did :-D

It's Ok, I"ll work on it
Do you mind reopening the issue?

**Comment by rgerum** [comment]
Well I like it as it is now. I think there is no harm in being able to go with enter from the username to the password field.

**Comment by rgerum** [comment]
Ah I saw that @onfranciis alrady created a pull request for this. So shall I accept the pull request then?
But I guess as it is now if you press ENTER in the username field, chances are that you have not typed the password yet. So I thought it might be the more expected behaviour.
But maybe we should go with the behaviour that most websites use, to assume it would be the "expected" behaviour.

**Comment by ptoro** [comment]
@rgerum, I think standard behavior is `<Enter>` anywhere in the form submits it. Most modern sites have this behavior: 

Wikipedia: `https://en.wikipedia.org/w/index.php?title=Special:UserLogin`
Reddit: `https://www.reddit.com/account/login`
Duolingo: `https://www.duolingo.com/log-in`

Some sites also focus the password field if you haven't entered anything, but I think that's out of the scope of this issue.

I propose just implementing the ability to press `<Enter>` anywhere in the login form to submit it.

**Comment by rgerum** [comment]
Ok then I agree. Just Enter anywhere to submit and that's it.

**Comment by ptoro** [comment]
Want to reopen the issue then?

**Comment by ptoro** [comment]
Just tested this. Doesn't look like it's working.

STR: 

1. Go to duostories.org
2. Click Log in button
3. Type username and press `<Tab>`
4. Type password and press `<Enter>`

Bug: nothing happens

**Comment by rgerum** [comment]
Oh yes it was only implemented for the editor. Should be done for the stories, too.

**Comment by ronran1** [comment]
Hey, just realized I'm still subscribed to this. I can take a look if you guys don't have this covered.

**Comment by ptoro** [comment]
Go for it! All contributions are welcome.

**Comment by ronran1** [comment]
Hi all, attempting to test my changes but I'm running into an "Editor Log in" dialog for approved contributors. Let me know when I can access this so I can test it out.

**Comment by ptoro** [comment]
Hi @ronran1, reposting this here in case you didn't see it in the Discord server:

> randrian 🇩🇪🇪🇸🇫🇷🇺🇸 — Yesterday at 10:03 PM
Great! Please assign yourself to the issue on github (if not already done) so everyone knows that you are already working on it :-)
And yes I would need your username for the duo stories.org website to give you access to the editor.

**Comment by ronran1** [comment]
> Hi @ronran1, reposting this here in case you didn't see it in the Discord server:

Thanks! I'm unable to self-assign this issue on Github.
