### ISSUE TITLE
Add 404 page for non-existant URLs

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#62]
For example, going to https://www.duostories.org/doesnotexist shows the follow instead of a 404 page:
<img width="639" alt="Screen Shot 2022-05-01 at 4 19 43 PM" src="https://user-images.githubusercontent.com/4418961/166163242-c9217826-bdf4-47ce-bf1b-0e323b8d394b.png">
Instead, a proper 404 page with a link to the home page should be shown.

**Comment by onfranciis** [comment]
I'm on it

**Comment by rgerum** [comment]
Well you would need the .htacess file for that I guess.

**Comment by onfranciis** [comment]
htaccess file because of PHP?
@ptoro

**Comment by rgerum** [comment]
Because of the Apache Server which handles the requests.

**Comment by onfranciis** [comment]
@rgerum I need help locating the main page, the component that is been loaded to the root (like the _App.js_).
That way I can see the possible links/pages to other parts of the site

**Comment by onfranciis** [comment]
I find it kind of impossible to implement because of the way it's built

Sorry for raising hopes high

**Comment by IFrzzl** [comment]
@rgerum If you added a 404 error redirect to lets say /404.html, we could just build a webpage there.

**Comment by rgerum** [comment]
I added
ErrorDocument 404 /?error=404
to the .htacess but now it just seems that it always links to the main page without the error code query. Maybe that is enough for building the 404 page. But the apache settings always confuse me a bit.

**Comment by IFrzzl** [comment]
> I added ErrorDocument 404 /?error=404 to the .htacess but now it just seems that it always links to the main page without the error code query. Maybe that is enough for building the 404 page. But the apache settings always confuse me a bit.

Do you think you could change it to a simple /404.html file? You can simply put this in the root. I'm not sure where you keep the API returns.

**Comment by rgerum** [comment]
I change the stories-app now to use a routing library and with this restructure I added a 404 response.

79aa553033ee2728404f054fb23b41715ee2eeae
