### ISSUE TITLE
add a dropdown to pick a different story in editor.duostories.org/?story=XXX

### ISSUE THREAD

**Issue by PaoloDiBello** [rgerum/unofficial-duolingo-stories#63]

**Comment by Danika-Dakika** [comment]
This looks like it stems from this request: https://discord.com/channels/726701782075572277/726701782537076790/970388161312215070 .
![image](https://github.com/rgerum/unofficial-duolingo-stories/assets/115673540/5f883a8f-6686-4046-a786-1fbb34c60003)

It is possible this could be useful for a course with few stories, but it would quickly become out-of-hand for a course with dozens. I  think that keeping the Editor menu open in another tab is a much simpler way to access other stories nearly as quickly.

**Comment by rgerum** [comment]
yes seems mainly relevant when quickly reviewing multiple stories to "switch to the next". So is it worth a feature or do we skip this one? The request has been a round for quite some time but it never seemed a priority so I did not come around to implement it yet.
