### ISSUE TITLE
In the editor, add export options for stories

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#66]
Exporting to a Google Doc seems like the most collaborative solution. Exporting to PDF may be another option to share the story but it likely would be more difficult to collaborate on a PDF.

**Comment by rgerum** [comment]
Well ideally everyone editing the stories should to so directly in the editor. I was thinking of adding collaborative editing (like google docs) there to avoid conficts when more people write at the same time.
I am not sure how exporting to Google Docs could look like. Especially for importing them back into the editor again.

**Comment by ptoro** [comment]
Ah, ok. Sounds like I misunderstood. I was thinking this was for sharing with people outside the editor. Should I close this one then?

**Comment by IFrzzl** [comment]
You could also just add an export to a .txt in the meantime

**Comment by rgerum** [comment]
I was thinking that having a way to just display the whole story (without needing to click on continue all the time) might just be enough. You could then use this to "print" the page to PDF to share if external collaborators for comments.

**Comment by ptoro** [comment]
Ah, @rgerum, sounds like you meant for me to add this as a part of the other issue: https://github.com/rgerum/unofficial-duolingo-stories/issues/65.

I still think @IFrzzl's suggestion is helpful.

**Comment by ptoro** [comment]
I just ran into a situation where this would be helpful. A friend who has a dad who's a native speaker offered to have his dad review some stories. There's a very low likelihood of my friend's dad ever joining and using the editor but he'd definitely be able to mark up a printed text file.

**Comment by rgerum** [comment]
I added two links directly below the "Cast" section in the editor to interactivly test the story and one to just display it like in the editor. When using the browsers print function it can thus be printed (or exported to pdf) to share for review.
