### ISSUE TITLE
Use a modern URL structure

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#67]
This is likely low priority, but would establish a good base for building future functionality off it.

Most modern web app URLs are structured so that the resource has a direct path to it. E.g.

Google Docs: `https://docs.google.com/document/d/<documentID>`
Discord: `https://discord.com/channels/<channelID>`
Duolingo: `https://www.duolingo.com/skill/<language>/<skillName>`

And resources have actions after that path:

Google Docs: `https://docs.google.com/document/d/<documentID>/edit`
Facebook: `https://www.facebook.com/marketplace/create/`

Currently Duostories.org uses a parameter to specify the story: `https://editor.duostories.org/?story=<storyID>`

Instead, something like 
`https://editor.duostories.org/story/<storyID>`
or
`https://editor.duostories.org/course/<courseID>`
would allow for further expansion of functionality.
E.g.
to edit a story: `https://editor.duostories.org/story/<storyID>/edit`
to preview a story: `https://editor.duostories.org/story/<storyID>/preview`

**Comment by ptoro** [comment]
I changed the title because I realized the story app would benefit from this as well.

**Comment by rgerum** [comment]
I implemented the url structure now for the stories-app 79aa553033ee2728404f054fb23b41715ee2eeae

TODO: implement the same for the editor-app
