### ISSUE TITLE
Importing from other languages (not just Spanish)

### ISSUE THREAD

**Issue by rgerum** [rgerum/unofficial-duolingo-stories#69]
The other official languages should also be imported from Duolingo into the Editor, so that when creating a new stroy it could be imported for translation from one of those official languages.

**Comment by ptoro** [comment]
I thought Spanish stories were the latest work from Duolingo. Is there a big use case for importing from other languages if the most up-to-date stories are all in Spanish?

**Comment by rgerum** [comment]
Well I guess for some contributors it might be easier to import from one of the other offical languages as they know those languages better. Also some stories might only be available in some languages, but I did not check that if this is still the case. It at least was some years ago the case.

**Comment by ptoro** [comment]
Ah, that makes sense.

**Comment by IFrzzl** [comment]
Randrian’s added this feature, simply use /import/{courseId}
