### ISSUE TITLE
Link to editor from index.html is broken.

### ISSUE THREAD

**Issue by IFrzzl** [rgerum/unofficial-duolingo-stories#72]
Leads to old editor, which comes up as 404.

**Comment by ptoro** [comment]
> Rupledo — Today at 9:13 AM
I'm not sue if you're aware, but the button to the editor on the homepage doesn't work.

1. Log in at https://www.duostories.org/ with an account that has permission to access the editor
2. Click Editor (the left-most button)
3. You're taken to a 404 page.

Looks like the link currently points to: https://www.duostories.org/old/editor_overview.html

---

Tatyana RU EN FR — Today at 1:39 PM
Hi, everyone! Tell me please how do we go to Editor? When I click on Editor button I "The requested URL not found"
