### ISSUE TITLE
"select the missing phrase" tests are broken in many stories

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#86]
This seems to be a pervasive bug. I think it has to do partly with the contributor not adding the necessary information. But when that happens, the app should be able to handle that situation better.

> maxmisch (🇺🇸 ➡ 🇷🇺) — 04/05/2022
I can't see the options for one of the questions in the 'Friends' Russian story. This also happened in the previous one called 'More Space' too. Maybe others after those two. I don't know.
![](https://media.discordapp.net/attachments/745203792764469289/960904170318204938/Screenshot_20220405-100920_Brave.jpg)

> Pineapple — Today at 1:23 PM
A lot of stories have broken "select the missing phrase" tests. The text content in the buttons are missing completely. Some specific stories where this is observed are  1302, 1294, 1167 and 1041.
![](https://media.discordapp.net/attachments/972722750672211989/973998907606597652/msedge_1Lx7qPPfw4.png)

> tinypancake — Today at 8:55 AM
Hi, not sure if this is the right channel but I noticed that in the Chinese story "Good Morning!" the options weren't showing for one of the questions.
![](https://media.discordapp.net/attachments/745203792764469289/973931296948641873/Screenshot_2022-05-11_at_8.53.41_PM.png)

**Comment by rgerum** [comment]
Ok resaved those stories (using a script) and now the issue is gone.
