### ISSUE TITLE
Font is missing

### ISSUE THREAD

**Issue by onfranciis** [rgerum/unofficial-duolingo-stories#87]
I know you're aware already, but can we have substitute fonts for now?

npm won't compile until the issue is resolved

Were they any fonts before? I can help in relocating them

**Comment by rgerum** [comment]
I thought I already addressed this issue in f383f1437718c1ea3c11df2c5efa283478b249a2
Maybe you could update and check if the issue is gone.
Let me know if there are problems remaining.
