### ISSUE TITLE
Incorrect "Main page" link after activation or password reset

### ISSUE THREAD

**Issue by PineappleSnackz** [rgerum/unofficial-duolingo-stories#88]
After successfully resetting or activating an account, the link that is supposed to direct you to the main page links to duostories.org/admin/index.html which doesn't seem to exist.

**Comment by rgerum** [comment]
If anyone wants to address this issue, start to look here:
https://github.com/rgerum/unofficial-duolingo-stories/blob/cd6f56d17db9b066f8be9af45ffa1f82e4c41baf/packages/stories-app/src/task.jsx#L71

**Comment by ptoro** [comment]
@ronran1 I saw you were interested in another good-first-issue. Interested in tackling this one?

**Comment by jahtomini** [comment]
Can I be assigned this?

**Comment by rgerum** [comment]
Yes, please go ahead. The workflow is basically roughly outlined here:
https://github.com/rgerum/unofficial-duolingo-stories#how-to-contribute
Create a fork, create a branch for the feature and then when you have changes committed, make pull request.
