### ISSUE TITLE
Blank screen after finishing a story, story not counted for user

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#90]
> maxmisch (🇺🇸 ➡ 🇷🇺) — Today at 3:54 PM
> I finished one of the Russian stories in Set 6, called The New Place, and it just gives me a blank screen at the end, then when I refresh, it doesn't show that it's completed. Tried it a few times and got the same result.

![image](https://user-images.githubusercontent.com/4418961/168453466-bc2dcdad-a8df-408d-a463-73881a380881.png)

**Comment by ptoro** [comment]
> maxmisch (🇺🇸 ➡ 🇷🇺) — Today at 3:26 PM
Now I get the Story Completed screen but it's not gold on the main screen.
The same thing is happening when I finish the next story called It's Too Dangerous.

**Comment by rgerum** [comment]
I found the error for the stories not being saved. But I did not find a problem with the Completion Screen, maybe it is already gone?
