### ISSUE TITLE
Sound generation from sentences containing ellipses

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#92]
> meticek — 05/14/2022
> There is a problem to generate sound from sentences containing character "…".
> I belive that problem is in this part of SSML code: `<sub alias="">text</sub>`
> Attribut alias cannot be empty.
> Try this instead: `<sub alias=" ">text</sub>` Should help.

![image](https://user-images.githubusercontent.com/4418961/168872737-9f9c69e0-a1af-43bd-8a2b-2297cca24424.png)

**Comment by rgerum** [comment]
Should have an easy potential fix if the suggestion fixes the issue:
https://github.com/rgerum/unofficial-duolingo-stories/blob/19b1e98aaacc7e435245d5841e16f6e5645aed3c/packages/editor-app/src/syntax_parser_new.mjs#L204
