### ISSUE TITLE
Disable clicking stories once a contributor has clicked one to import it

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#95]
After a contributor clicks Import to add a story, they can select from a list of stories to import:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/4418961/170803880-c188ced3-8672-475d-aaaf-2aa1b02279af.png">

Once they click on a story from the list there's a delay before the next screen is loaded that causes them to think their click wasn't registered so they click again. This imports the story twice--once for each click.
![image](https://user-images.githubusercontent.com/4418961/170803974-95f85d68-cf5f-4b1e-b9f9-b724f1466cfd.png)

Possible solution: disable the stories in list so they can't be clicked once one has been clicked.

Originally reported by:
>Kosovo (Telugu Contributor) — Today at 6:53 PM
when i tried to import a story it made two copies
am i the only one experiencing this issue?

And I was able to reproduce this.

**Comment by rgerum** [comment]
Yes, the solution sounds reasonable.
