### ISSUE TITLE
Allow contributors to delete imported stories 

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#96]
Once a contributor has imported a story, there's no way to remove it currently.

This functionality is helpful in case two contributors accidentally add the same story, one contributor adds the same story twice, or a story has been abandoned and no longer has a contributor that wishes to translate it.

**Comment by rgerum** [comment]
Yes I agree this should be possible to delete the stories. I was a bit hesitant to implement it to prevent contributors from accidentally (or even maliciously) deleting good stories.

**Comment by ptoro** [comment]
Good point about the malicious case. It's probably important to have a log of which users have deleted a story and make that log visible to contributors so they know who to reach out to in case a story gets deleted.

**Comment by IFrzzl** [comment]
@rgerum To solve the accidentally, there can be a simple confirm delete pop up before it sends the request.  @ptoro The malicious one is already solved - [in the stories content repo](https://github.com/rgerum/unofficial-duolingo-stories-content), we can simply rollback the commits.
