### ISSUE TITLE
The Author field for stories in the editor is now always "official"

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#97]
It was previously randriano but now is official (though neither of those seem correct):
<img width="289" alt="image" src="https://user-images.githubusercontent.com/4418961/170804165-055d0827-ffc3-4e15-b8a8-4b699bcf61ca.png">

It seems the author field should be the name of the contributor that marked it for feedback.

**Comment by rgerum** [comment]
Hmm yes probably that would make sense. Currently it should be the one who imported the story, though it might be broken.
