### ISSUE TITLE
Silesian flag colors are a little off

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#98]
> DziouchaZWężemNaGowie — Today at 8:33 PM
Although now that I look at it, the shades are a little off. The proper flag looks like that:
![image](https://user-images.githubusercontent.com/4418961/170898419-43f26162-b522-4717-b7f4-77828a7ff469.png)

**Comment by rgerum** [comment]
I make the flags line up with the color scheme Duolingo uses so I will keep the colors as they ate currently. Its a design choice by Duolingo which I want to follow.
